### PR TITLE
Fix scrollToElement to only accept ID (without #).

### PR DESCRIPTION
**Pull request by Markieta**
Fixes [Left nav buttons fail when name contains a dot (.) #796](https://github.com/sighupio/gatekeeper-policy-manager/issues/796)

### CODE REVIEW

**Comment by Markieta** [comment]
Bumped the `appVersion` but not the chart version as per your doc.

Let me know if that's sufficient, or if there's anything else I can do to make it smoother next time (e.g., adding a release doc).

**Review by ralgozino — CHANGES_REQUESTED** [review]
Hi Markieta,

Nice catch on the bug and thanks for the PR!

The fix proposed can't be merged, it breaks navigation in two ways:
1. External links pointing to a specific Constraint Template (for example, `https://gpm/constrainttemplates#MyConstraintTemplate` don't scroll anymore to the right place
2. In each Constraint of the Constraints view there's a link to the corresponding template that uses the anchor notation (`#<TemplateName>`) so you can go easily from the constraint to the template it is based on. This would not work anymore.

I need some time to think about a proper fix (maybe url-encoding the dot to `%2E` is enough?)

pinging @Al-Pragliola for ideas


> Bumped the `appVersion` but not the chart version as per your doc.
> 
> Let me know if that's sufficient, or if there's anything else I can do to make it smoother next time (e.g., adding a release doc).

Don't worry about bumping and preparing things for the release, we can take care of that part. The PR with the fix is more than enough 🙌 

Nitpick: it would be nice if you can adopt [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) for the commits messages in the future

Thanks!

**Comment by Markieta** [comment]
> I need some time to think about a proper fix (maybe url-encoding the dot to `%2E` is enough?)

Good points. While URL encoding does fix the linking problem `https://gpm/constrainttemplates#My%2EConstraint%2ETemplate` (periods also work here: `https://gpm/constrainttemplates#My.Constraint.Template`), the `querySelector` breaks trying to find the `id`.

> Don't worry about bumping and preparing things for the release, we can take care of that part. The PR with the fix is more than enough 🙌

Sounds good, I reverted the bump as this might take longer to fix.

> Nitpick: it would be nice if you can adopt [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) for the commits messages in the future

Oh neat, I'll try to follow this more often, thanks!

**Comment by Markieta** [comment]
Updated to use `document.querySelector(hash.replace(/:|\./g, '\\$&'))`.

This escapes periods (.) and colons (:) which seem to be the only problematic ([allowable](https://www.w3.org/TR/html4/types.html#:~:text=ID%20and%20NAME%20tokens%20must,tokens%20defined%20by%20other%20attributes.)) characters used for IDs. 

> 1. External links pointing to a specific Constraint Template (for example, `https://gpm/constrainttemplates#MyConstraintTemplate` don't scroll anymore to the right place
> 2. In each Constraint of the Constraints view there's a link to the corresponding template that uses the anchor notation (`#<TemplateName>`) so you can go easily from the constraint to the template it is based on. This would not work anymore.

Works for both of these scenarios now as well (tested with Chrome 115.0.5790.170 and Firefox 116.0).

**Review by ralgozino — APPROVED** [review]
LGTM

thank you, Christopher!

**Pull request merged**
